# Generated by Django 4.2.24 on 2025-09-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_update_model_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='yumhistory',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
