# Generated by Django 4.2.24 on 2025-09-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('action', models.CharField(max_length=20)),
                ('package_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'yum_history',
            },
        ),
    ]
